# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logging.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'logging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\x12\x07logging\"%\n\nLogRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"-\n\x0bLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"$\n\x10MessagesResponse\x12\x10\n\x08messages\x18\x01 \x03(\t2\x83\x01\n\x0eLoggingService\x12\x37\n\nLogMessage\x12\x13.logging.LogRequest\x1a\x14.logging.LogResponse\x12\x38\n\x0bGetMessages\x12\x0e.logging.Empty\x1a\x19.logging.MessagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=26
  _globals['_LOGREQUEST']._serialized_end=63
  _globals['_LOGRESPONSE']._serialized_start=65
  _globals['_LOGRESPONSE']._serialized_end=110
  _globals['_EMPTY']._serialized_start=112
  _globals['_EMPTY']._serialized_end=119
  _globals['_MESSAGESRESPONSE']._serialized_start=121
  _globals['_MESSAGESRESPONSE']._serialized_end=157
  _globals['_LOGGINGSERVICE']._serialized_start=160
  _globals['_LOGGINGSERVICE']._serialized_end=291
# @@protoc_insertion_point(module_scope)
